# Generated by Django 5.0 on 2024-07-25 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edtAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDepartement', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomSalle', models.CharField(max_length=50)),
                ('batiment', models.CharField(max_length=50)),
                ('lieu', models.CharField(max_length=50)),
                ('est_libre', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='professeur',
            name='contact',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='prenom',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomModule', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edtAPI.departement')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edtAPI.professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomNiveau', models.CharField(max_length=20)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edtAPI.departement')),
            ],
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edtAPI.professeur')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edtAPI.module')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edtAPI.niveau')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edtAPI.salle')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('emploi_du_temps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edtAPI.emploidutemps')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edtAPI.salle')),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='edtAPI_rese_date_a44d0b_idx'), models.Index(fields=['salle'], name='edtAPI_rese_salle_i_31e3ca_idx'), models.Index(fields=['heure_debut'], name='edtAPI_rese_heure_d_3f384b_idx'), models.Index(fields=['heure_fin'], name='edtAPI_rese_heure_f_e4f589_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='emploidutemps',
            index=models.Index(fields=['jour'], name='edtAPI_empl_jour_ae5d9b_idx'),
        ),
        migrations.AddIndex(
            model_name='emploidutemps',
            index=models.Index(fields=['heure_debut'], name='edtAPI_empl_heure_d_035b81_idx'),
        ),
        migrations.AddIndex(
            model_name='emploidutemps',
            index=models.Index(fields=['heure_fin'], name='edtAPI_empl_heure_f_c02dcf_idx'),
        ),
    ]
