# Generated by Django 5.0.7 on 2024-08-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edtAPI', '0003_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_user', models.CharField(max_length=50)),
                ('prenom_user', models.CharField(max_length=50)),
                ('passmot', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
